name = "autorag-worker"
main = "src/index.ts"
compatibility_date = "2024-01-15"
# account_id is loaded from CLOUDFLARE_ACCOUNT_ID environment variable

# Default vars (used when no --env is specified)
[vars]
# AUTORAG_INSTANCE will be set from environment variable
GATEWAY_NAME = "autorag-gateway"
ENVIRONMENT = "development"

# Production environment  
[env.production.vars]
# AUTORAG_INSTANCE will be set from environment variable
GATEWAY_NAME = "autorag-gateway"
ENVIRONMENT = "production"

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "library-docs-01" # This should match your R2_BUCKET_NAME in .env

# AI binding for AutoRAG
[ai]
binding = "AI"

# KV namespace for session storage (optional)
# [[kv_namespaces]]
# binding = "SESSIONS"
# id = "your-kv-namespace-id"

# Secrets to be added via CLI:
# wrangler secret put OPENAI_API_KEY
# wrangler secret put ANTHROPIC_API_KEY